version: '3'

env:
    CURDIR:
        sh: pwd
    REPJ: tmp/repos.json

tasks:
    default:
        cmds:
            - task: serve

    fetch_repos_json:
        desc: fetch repo data json from github api
        cmds:
            - cmd: >-
                got --output {{.CURDIR}}/{{.REPJ}}
                https://api.github.com/users/triole/repos?page=1&per_page=1000

    serve:
        desc: run local server
        cmds:
            - cmd: caddy file-server --listen :8989
